apiVersion: v1
kind: Service
metadata:
  name:  zetos-rtp-service
  namespace: zetos
spec:
  type: NodePort
  selector:
    app: zetos-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
